### ISSUE TITLE
Warnings when dog teleports through (nether) portal

### ISSUE THREAD

**Issue by FPSUsername** [DoggyCraft/MyDog#23]
### Information
**Server version:** [PurPur](purpur.pl3x.net/) v1.17.1 build 2165
**MyDog version:** v0.1.1-alpha
**Java version:** [AdoptOpenJDK 16 OpenJ9](https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=openj9)

### Issue
When the owned dog enters a nether portal and the player doesn't, the server console generates a warning and an illegal argument exception.
I'm not sure if it's intended that the dog stays in the nether, but it returned back into the overworld once I slept in a bed.
This log continued every 10 seconds till the tog returned.

### Log
```log
[22:26:11] [Server thread/WARN]: [MyDog] Task #83 for MyDog v0.1.1-alpha generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between Survival and Spawn_nether
	at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.17.1.jar:git-Purpur-1265]
	at org.bukkit.Location.distance(Location.java:493) ~[patched_1.17.1.jar:git-Purpur-1265]
	at dk.fido2603.mydog.MyDog$1.run(MyDog.java:254) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1265]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Purpur-1265]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1265]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1265]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1265]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1265]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1265]
	at net.minecraft.server.MinecraftServer$$Lambda$3667/0x00000000acf4bb58.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by HeroGamers** [comment]
Hi there!

Thanks for the bug report!
I haven't been that active on the project lately, due to work and school, but whenever I get back to the project I will be sure to give it a look!
If it's breaking too much stuff and making the plugin unusable, I'll take a look at it as soon as I get some time to do so.

Cheers,
Hero
